import Foundation

/// One ingredient line of a meal, resolved against the household stock.
nonisolated struct MealIngredient: Identifiable, Codable, Hashable, Sendable {
    var id: UUID = UUID()
    var name: String
    var quantityText: String
    var category: FoodCategory = .grocery
    /// Estimated euro price if the user has to buy it.
    var estimatedPrice: Double = 0
    /// Pantry basics (salt, pepper, oil, water) that never count as a purchase.
    var isStaple: Bool = false
    /// Filled by `MealEngine.resolve` — never trusted from the model itself.
    var inStock: Bool = false
    var matchedItemID: UUID?
    /// Share of one stock unit consumed when cooking, e.g. 0.5 for half a pack.
    var stockUsage: Double = 1

    nonisolated var isFree: Bool { inStock || isStaple }
}

/// Where a meal suggestion comes from.
nonisolated enum MealSource: String, Codable, Sendable {
    case ai
    case curated
}

/// A meal SAVEAT proposes, generated by the assistant or curated in the app.
nonisolated struct Meal: Identifiable, Codable, Hashable, Sendable {
    var id: UUID = UUID()
    var name: String
    var emoji: String = "🍽️"
    var summary: String = ""
    /// Bundled illustration name, when a curated photo exists.
    var imageName: String?
    var prepMinutes: Int = 10
    var cookMinutes: Int = 10
    var difficulty: String = "Facile"
    var servings: Int = 2
    var kcalPerServing: Int = 0
    var proteinsPerServing: Int = 0
    var ingredients: [MealIngredient] = []
    var steps: [String] = []
    var tags: [String] = []
    /// Why this meal helps right now, e.g. "Utilise ton jambon ouvert".
    var antiWasteNote: String?
    var source: MealSource = .curated
    /// Inventory items this meal would consume, filled by `MealEngine.resolve`.
    var rescuedItemIDs: [UUID] = []
    /// Freshness of the most urgent item used, filled by `MealEngine.resolve`.
    var topUrgency: FreshnessState = .fresh

    // MARK: Derived

    nonisolated var totalMinutes: Int { prepMinutes + cookMinutes }

    nonisolated var timeText: String { "\(totalMinutes) min" }

    nonisolated var availableIngredients: [MealIngredient] {
        ingredients.filter(\.isFree)
    }

    nonisolated var missingIngredients: [MealIngredient] {
        ingredients.filter { !$0.isFree }
    }

    nonisolated var extraCost: Double {
        missingIngredients.reduce(0) { $0 + $1.estimatedPrice }
    }

    nonisolated var extraCostPerServing: Double {
        guard servings > 0 else { return extraCost }
        return extraCost / Double(servings)
    }

    nonisolated var isZeroEuro: Bool { missingIngredients.isEmpty }

    nonisolated var availabilityText: String {
        isZeroEuro
            ? "Tu as tout ce qu'il faut"
            : "\(availableIngredients.count)/\(ingredients.count) ingrédients chez toi"
    }

    /// Higher is better: rescues expiring food, uses the stock, costs little, stays simple.
    nonisolated var score: Double {
        let availability = Double(availableIngredients.count) / Double(max(ingredients.count, 1)) * 100
        let urgency: Double
        switch topUrgency {
        case .urgent: urgency = 60
        case .soon: urgency = 28
        case .fresh: urgency = 0
        }
        let stockDepth = Double(rescuedItemIDs.count) * 6
        let costPenalty = extraCost * 7
        let speed = totalMinutes <= 20 ? 8.0 : 0
        return availability + urgency + stockDepth - costPenalty + speed
    }
}

/// One line of the "update my stock" screen after cooking.
nonisolated struct StockDeduction: Identifiable, Hashable, Sendable {
    var id: UUID { itemID }
    var itemID: UUID
    var name: String
    var emoji: String
    var unit: String
    var before: Double
    var used: Double

    nonisolated var after: Double { max(before - used, 0) }
}

/// Decoding shape for the assistant's JSON answer.
nonisolated struct MealAIPayload: Decodable, Sendable {
    nonisolated struct IngredientDTO: Decodable, Sendable {
        var name: String
        var quantityText: String?
        var estimatedPrice: Double?
        var isStaple: Bool?
    }

    nonisolated struct MealDTO: Decodable, Sendable {
        var name: String
        var emoji: String?
        var summary: String?
        var prepMinutes: Int?
        var cookMinutes: Int?
        var difficulty: String?
        var servings: Int?
        var kcalPerServing: Int?
        var proteinsPerServing: Int?
        var tags: [String]?
        var antiWasteNote: String?
        var ingredients: [IngredientDTO]
        var steps: [String]
    }

    var message: String?
    var meals: [MealDTO]
}

extension MealAIPayload.MealDTO {
    /// Converts the model answer into an app meal. Stock matching happens later.
    nonisolated func toMeal() -> Meal {
        Meal(
            name: name,
            emoji: emoji ?? "🍽️",
            summary: summary ?? "",
            prepMinutes: max(prepMinutes ?? 5, 0),
            cookMinutes: max(cookMinutes ?? 10, 0),
            difficulty: difficulty ?? "Facile",
            servings: max(servings ?? 2, 1),
            kcalPerServing: max(kcalPerServing ?? 0, 0),
            proteinsPerServing: max(proteinsPerServing ?? 0, 0),
            ingredients: ingredients.map { dto in
                MealIngredient(
                    name: dto.name,
                    quantityText: dto.quantityText ?? "",
                    estimatedPrice: max(dto.estimatedPrice ?? 0, 0),
                    isStaple: dto.isStaple ?? false
                )
            },
            steps: steps,
            tags: tags ?? [],
            antiWasteNote: antiWasteNote,
            source: .ai
        )
    }
}
