// Config.swift - Auto-generated at build time
// Virtual read-only view of public environment variables available to Swift code.
//
// The string literals below are INTENTIONALLY EMPTY in source control —
// the real values are injected at iOS build time. Do not edit this file
// to add values, and do not inspect it to discover env values (you will
// only ever see ""). To find a value at agent-time, look up the env name
// in the project's .env file or in the Rork agent's environment listing.

import Foundation

enum Config {
    static let EXPO_PUBLIC_REVENUECAT_IOS_API_KEY = ""
    /// Read from the app's own Info.plist at runtime instead of a literal,
    /// so a local, gitignored `Secrets.xcconfig` can supply the real Rork
    /// Toolkit key on a developer's own machine without it ever touching
    /// source control (see `RorkToolkitSecretKey` in the target's Info
    /// tab). Empty when that isn't configured — same behavior as the
    /// literal it replaces.
    static var EXPO_PUBLIC_RORK_TOOLKIT_SECRET_KEY: String {
        Bundle.main.object(forInfoDictionaryKey: "RorkToolkitSecretKey") as? String ?? ""
    }
    static let EXPO_PUBLIC_TOOLKIT_URL = ""

    static let allValues: [String: String] = [
        "EXPO_PUBLIC_REVENUECAT_IOS_API_KEY": EXPO_PUBLIC_REVENUECAT_IOS_API_KEY,
        "EXPO_PUBLIC_RORK_TOOLKIT_SECRET_KEY": EXPO_PUBLIC_RORK_TOOLKIT_SECRET_KEY,
        "EXPO_PUBLIC_TOOLKIT_URL": EXPO_PUBLIC_TOOLKIT_URL,
    ]
}
