import Foundation

/// Fictional French places for development and previews.
///
/// Every entry is invented for SAVEAT and marked `isTestData: true` — no
/// address, phone number, or offer here comes from a real business, and none
/// is scraped or copied from any third-party service (§18). Once a real
/// source (Open Data, a partner API, the SAVEAT backend…) is ready, it
/// implements `AntiWastePlacesProviding` and replaces this service in
/// `AntiWasteRepository.shared` — nothing else changes.
nonisolated struct MockAntiWastePlacesService: AntiWastePlacesProviding {
    func places() async -> [AntiWastePlace] {
        Self.all
    }

    nonisolated static let all: [AntiWastePlace] = [
        AntiWastePlace(
            id: "test-panier-solidaire-paris",
            name: "Le Panier Solidaire",
            category: .basket,
            latitude: 48.8606, longitude: 2.3376,
            address: "12 Rue des Écoles",
            city: "Paris",
            postalCode: "75005",
            description: "Panier de fruits et légumes invendus, composé chaque matin par les commerçants du quartier.",
            openingHours: "Lun–Sam 9h–13h",
            websiteURLString: nil,
            phone: nil,
            partnerName: nil,
            offerTitle: "Panier surprise",
            offerDescription: "Environ 3 kg de fruits et légumes de saison.",
            imageURLString: nil,
            isPartner: true,
            isFeatured: true,
            isTestData: true
        ),
        AntiWastePlace(
            id: "test-frigo-solidaire-belleville",
            name: "Frigo Solidaire Belleville",
            category: .communityFridge,
            latitude: 48.8722, longitude: 2.3820,
            address: "45 Rue de Belleville",
            city: "Paris",
            postalCode: "75019",
            description: "Frigo partagé en libre accès — chacun peut y déposer ou y prendre de la nourriture encore bonne.",
            openingHours: "Ouvert 24h/24",
            websiteURLString: nil,
            phone: nil,
            partnerName: nil,
            offerTitle: nil,
            offerDescription: nil,
            imageURLString: nil,
            isPartner: false,
            isFeatured: false,
            isTestData: true
        ),
        AntiWastePlace(
            id: "test-epicerie-antigaspi-marais",
            name: "Épicerie Zéro Perte",
            category: .antiWasteStore,
            latitude: 48.8584, longitude: 2.3620,
            address: "8 Rue des Rosiers",
            city: "Paris",
            postalCode: "75004",
            description: "Épicerie spécialisée dans les produits proches de leur date, à prix réduit.",
            openingHours: "Mar–Dim 10h–19h",
            websiteURLString: "https://example.com",
            phone: "01 23 45 67 89",
            partnerName: "Épicerie Zéro Perte",
            offerTitle: "-30 % sur les produits du jour",
            offerDescription: "Sélection renouvelée chaque matin selon les dates de péremption.",
            imageURLString: nil,
            isPartner: true,
            isFeatured: false,
            isTestData: true
        ),
        AntiWastePlace(
            id: "test-asso-partage-oberkampf",
            name: "Association Partage & Compagnie",
            category: .association,
            latitude: 48.8656, longitude: 2.3736,
            address: "22 Rue Oberkampf",
            city: "Paris",
            postalCode: "75011",
            description: "Distribution alimentaire solidaire, ouverte à toutes et tous sans condition.",
            openingHours: "Jeu 17h–19h",
            websiteURLString: nil,
            phone: nil,
            partnerName: nil,
            offerTitle: nil,
            offerDescription: nil,
            imageURLString: nil,
            isPartner: false,
            isFeatured: false,
            isTestData: true
        ),
        AntiWastePlace(
            id: "test-boulangerie-partenaire-lyon",
            name: "Boulangerie Au Bon Levain",
            category: .partner,
            latitude: 45.7640, longitude: 4.8357,
            address: "3 Rue de la République",
            city: "Lyon",
            postalCode: "69002",
            description: "Boulangerie partenaire SAVEAT — invendus du jour à prix réduit en fin de journée.",
            openingHours: "Lun–Sam 7h–19h30",
            websiteURLString: nil,
            phone: nil,
            partnerName: "Au Bon Levain",
            offerTitle: "Panier du soir à -50 %",
            offerDescription: "Pain et viennoiseries de la journée, disponibles après 18h30.",
            imageURLString: nil,
            isPartner: true,
            isFeatured: true,
            isTestData: true
        ),
        AntiWastePlace(
            id: "test-marche-bon-plan-lyon",
            name: "Marché de la Guillotière",
            category: .deal,
            latitude: 45.7551, longitude: 4.8390,
            address: "Place du Pont",
            city: "Lyon",
            postalCode: "69007",
            description: "Fin de marché avec prix cassés sur les fruits et légumes restants.",
            openingHours: "Mar, Jeu, Dim 12h–13h",
            websiteURLString: nil,
            phone: nil,
            partnerName: nil,
            offerTitle: nil,
            offerDescription: nil,
            imageURLString: nil,
            isPartner: false,
            isFeatured: false,
            isTestData: true
        ),
        AntiWastePlace(
            id: "test-restaurant-antigaspi-bordeaux",
            name: "Restaurant Fin de Frigo",
            category: .restaurant,
            latitude: 44.8412, longitude: -0.5805,
            address: "17 Cours de l'Intendance",
            city: "Bordeaux",
            postalCode: "33000",
            description: "Restaurant qui cuisine chaque jour avec les invendus des producteurs locaux.",
            openingHours: "Mar–Sam 12h–14h, 19h–22h",
            websiteURLString: "https://example.com",
            phone: nil,
            partnerName: "Fin de Frigo",
            offerTitle: nil,
            offerDescription: nil,
            imageURLString: nil,
            isPartner: true,
            isFeatured: false,
            isTestData: true
        ),
        AntiWastePlace(
            id: "test-panier-solidaire-bordeaux",
            name: "Panier Anti-Gaspi Bordeaux",
            category: .basket,
            latitude: 44.8378, longitude: -0.5792,
            address: "12 Rue Sainte-Catherine",
            city: "Bordeaux",
            postalCode: "33000",
            description: "Panier hebdomadaire composé des surplus de trois commerces du centre-ville.",
            openingHours: "Ven 16h–18h",
            websiteURLString: nil,
            phone: nil,
            partnerName: nil,
            offerTitle: "Panier de la semaine",
            offerDescription: "Composition variable selon les surplus de la semaine.",
            imageURLString: nil,
            isPartner: true,
            isFeatured: false,
            isTestData: true
        ),
        AntiWastePlace(
            id: "test-frigo-solidaire-marseille",
            name: "Frigo Partagé du Panier",
            category: .communityFridge,
            latitude: 43.2989, longitude: 5.3667,
            address: "9 Montée des Accoules",
            city: "Marseille",
            postalCode: "13002",
            description: "Frigo solidaire installé par les habitants du quartier du Panier.",
            openingHours: "Ouvert 24h/24",
            websiteURLString: nil,
            phone: nil,
            partnerName: nil,
            offerTitle: nil,
            offerDescription: nil,
            imageURLString: nil,
            isPartner: false,
            isFeatured: false,
            isTestData: true
        ),
        AntiWastePlace(
            id: "test-epicerie-antigaspi-lille",
            name: "Épicerie Seconde Vie",
            category: .antiWasteStore,
            latitude: 50.6292, longitude: 3.0573,
            address: "5 Rue de Béthune",
            city: "Lille",
            postalCode: "59000",
            description: "Épicerie de produits déclassés ou proches de leur date, à petit prix.",
            openingHours: "Lun–Sam 10h–19h",
            websiteURLString: nil,
            phone: nil,
            partnerName: "Seconde Vie",
            offerTitle: "Jusqu'à -40 %",
            offerDescription: "Sur toute la sélection anti-gaspi du magasin.",
            imageURLString: nil,
            isPartner: true,
            isFeatured: false,
            isTestData: true
        ),
        AntiWastePlace(
            id: "test-asso-partage-toulouse",
            name: "Les Restos du Cœur — Antenne Capitole",
            category: .association,
            latitude: 43.6047, longitude: 1.4442,
            address: "2 Place du Capitole",
            city: "Toulouse",
            postalCode: "31000",
            description: "Distribution alimentaire et accompagnement social, ouverts à tous.",
            openingHours: "Mer 14h–17h",
            websiteURLString: nil,
            phone: nil,
            partnerName: nil,
            offerTitle: nil,
            offerDescription: nil,
            imageURLString: nil,
            isPartner: false,
            isFeatured: false,
            isTestData: true
        ),
        AntiWastePlace(
            id: "test-primeur-partenaire-nantes",
            name: "Primeur Croc'Saison",
            category: .partner,
            latitude: 47.2184, longitude: -1.5536,
            address: "10 Rue Crébillon",
            city: "Nantes",
            postalCode: "44000",
            description: "Primeur partenaire SAVEAT, cagette de fruits et légumes mûrs à consommer vite.",
            openingHours: "Mar–Dim 8h–13h",
            websiteURLString: nil,
            phone: nil,
            partnerName: "Croc'Saison",
            offerTitle: "Cagette à prix réduit",
            offerDescription: "Fruits et légumes mûrs à point, à consommer dans les 2–3 jours.",
            imageURLString: nil,
            isPartner: true,
            isFeatured: true,
            isTestData: true
        )
    ]
}
